package router

import (
	"jarvis/controllers"

	"github.com/gofiber/contrib/v3/swaggo"
	"github.com/gofiber/fiber/v3"
)

// Setup configures all application routes.
func Setup(app *fiber.App) {

	v1 := app.Group("/v1")

	tasks := v1.Group("/tasks")
	tasks.Get("/", controllers.GetTasks)
	tasks.Post("/", controllers.CreateTask)
	tasks.Get("/:id", controllers.GetTask)
	tasks.Patch("/:id", controllers.UpdateTask)
	tasks.Delete("/:id", controllers.DeleteTask)

	// OpenAPI doc.json generated by swag init. Tell frontend Agent to read it to know our API
	v1.Get("/swagger/doc.json", func(c fiber.Ctx) error {
		return c.SendFile("docs/swagger/swagger.json")
	})
	// Swagger UI dashboard
	v1.Get("/swagger/*", swaggo.New())

	conversations := v1.Group("/conversations")
	conversations.Get("/", controllers.GetConversations)
	conversations.Post("/", controllers.CreateConversation)
	conversations.Get("/:id", controllers.GetConversation)
	conversations.Patch("/:id", controllers.UpdateConversation)
	conversations.Delete("/:id", controllers.DeleteConversation)

	messages := conversations.Group("/:id/messages")
	messages.Get("/", controllers.GetMessages)
	messages.Post("/", controllers.SendMessage)

}
